apiVersion: apps/v1
kind: Deployment
metadata:
  name: paulo
  labels:
    app: paulo
    type: stremio-bot
  namespace: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paulo
  template:
    metadata:
      labels:
        app: paulo
    spec:
      containers:
      - name: paulo
        image: sleeyax/paulo:v0.0.6
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: paulosecrets
              key: token
        - name: DISCORD_PREFIX
          valueFrom:
            secretKeyRef:
              name: paulosecrets
              key: prefix